# Generated by Django 5.1.6 on 2025-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_phone_remove_user_tg_nick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id сессии'),
        ),
    ]
