# Generated by Django 5.1.6 on 2025-03-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription_course_subscription_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.lesson'),
        ),
    ]
